# Generated By: Claude Code (Claude Opus 4.6)
PYTHON := python

.PHONY: all check install-dev markdown-lint links reachability help

all: check  ## Run all checks (default)

check: markdown-lint links reachability  ## Run all validation

install-dev:  ## Install development dependencies
	$(PYTHON) -m pip install --quiet -e '.[dev]'

markdown-lint: install-dev  ## Lint markdown files
	$(PYTHON) -m pymarkdown --disable-rules MD013,MD024,MD031,MD036 scan .

links:  ## Validate local markdown links and anchors
	$(PYTHON) scripts/check-links.py

reachability:  ## Verify all files are reachable from entry points
	@echo "Checking document reachability..."
	$(PYTHON) scripts/reachability.py --check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := all
