#!/usr/bin/python
# Generated By: Claude Code (Claude Opus 4.6)
# Licensed under Apache 2.0
#
# Fetch calendar events with full attendee data.
#
# Usage: calendar-brief.py [YYYY-MM-DD] [calendar_id]
#   Defaults to today and "primary" if not given.
#
# events list strips attendees for group-calendar events.
# This script does events list then events get on each to get full data.
# Output: JSON array of events with attendees and response status.

import json
import subprocess
import sys
from datetime import datetime, timedelta


def run_gws(*args):
    result = subprocess.run(
        list(args),
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: {' '.join(args)}: {result.stderr}", file=sys.stderr)
        return None
    output = result.stdout
    for i, line in enumerate(output.splitlines()):
        if line.strip().startswith("{"):
            output = "\n".join(output.splitlines()[i:])
            break
    return json.loads(output)


def get_events(date_str: str, calendar_id: str = "primary") -> list:
    local_date = datetime.strptime(date_str, "%Y-%m-%d")
    tz_offset = local_date.astimezone().strftime("%z")
    tz_offset = tz_offset[:3] + ":" + tz_offset[3:]
    time_min = f"{date_str}T00:00:00{tz_offset}"
    next_day = (local_date + timedelta(days=1)).strftime("%Y-%m-%d")
    time_max = f"{next_day}T00:00:00{tz_offset}"

    listing = run_gws(
        "gws", "calendar", "events", "list",
        "--params", json.dumps({
            "calendarId": calendar_id,
            "singleEvents": True,
            "orderBy": "startTime",
            "timeMin": time_min,
            "timeMax": time_max,
        }),
    )
    if not listing:
        return []

    events = []
    for item in listing.get("items", []):
        if item.get("eventType") == "workingLocation":
            continue

        event_id = item.get("id")
        if not event_id:
            continue

        full = run_gws(
            "gws", "calendar", "events", "get",
            "--params", json.dumps({
                "calendarId": calendar_id,
                "eventId": event_id,
            }),
        )
        if full:
            events.append(full)
        else:
            events.append(item)

    return events


def summarize(events: list) -> list:
    summary = []
    for event in events:
        entry = {
            "time": event.get("start", {}).get("dateTime", event.get("start", {}).get("date", "")),
            "end": event.get("end", {}).get("dateTime", event.get("end", {}).get("date", "")),
            "title": event.get("summary", "(no title)"),
        }

        attendees = event.get("attendees", [])
        self_status = "accepted"
        for a in attendees:
            if a.get("self"):
                self_status = a.get("responseStatus", "needsAction")
                break
        entry["responseStatus"] = self_status

        if attendees:
            entry["attendees"] = []
            for a in attendees:
                if a.get("resource"):
                    continue
                att = {
                    "email": a.get("email", ""),
                    "status": a.get("responseStatus", "unknown"),
                }
                if a.get("displayName"):
                    att["name"] = a["displayName"]
                if a.get("comment"):
                    att["comment"] = a["comment"]
                if a.get("optional"):
                    att["optional"] = True
                if a.get("self"):
                    att["self"] = True
                entry["attendees"].append(att)

        attachments = event.get("attachments", [])
        if attachments:
            entry["attachments"] = [
                {"title": att.get("title", ""), "url": att.get("fileUrl", "")}
                for att in attachments
            ]

        if event.get("hangoutLink"):
            entry["meetLink"] = event["hangoutLink"]

        summary.append(entry)

    return summary


def main():
    if len(sys.argv) > 3:
        print("Usage: calendar-brief.py [YYYY-MM-DD] [calendar_id]")
        sys.exit(1)

    date_str = sys.argv[1] if len(sys.argv) >= 2 else datetime.now().strftime("%Y-%m-%d")
    calendar_id = sys.argv[2] if len(sys.argv) >= 3 else "primary"

    events = get_events(date_str, calendar_id)
    result = summarize(events)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
