#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
# Licensed under Apache 2.0
"""Fetch meetings with response status from Google Calendar.

Wraps `gws calendar events list` with proper --params JSON, extracts
the authenticated user's responseStatus per event, and outputs a clean
table or JSON.

Usage:
    fetch-meeting-status.py --today
    fetch-meeting-status.py --tomorrow
    fetch-meeting-status.py 2026-04-17
    fetch-meeting-status.py --json --today
    fetch-meeting-status.py --calendar-id other@example.com --today

Output (table, default):
    08:00-08:30     accepted         Daily Sync
    09:15-10:00     declined         Architecture Review
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timedelta, timezone


def get_local_utc_offset() -> str:
    now = datetime.now(timezone.utc).astimezone()
    offset = now.utcoffset()
    total_seconds = int(offset.total_seconds())
    sign = "+" if total_seconds >= 0 else "-"
    total_seconds = abs(total_seconds)
    hours, remainder = divmod(total_seconds, 3600)
    minutes = remainder // 60
    return f"{sign}{hours:02d}:{minutes:02d}"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Fetch meetings with response status from Google Calendar"
    )
    parser.add_argument(
        "date",
        nargs="?",
        default=None,
        help="Date to fetch (YYYY-MM-DD). Default: today.",
    )
    parser.add_argument(
        "--today",
        action="store_true",
        help="Fetch today's meetings",
    )
    parser.add_argument(
        "--tomorrow",
        action="store_true",
        help="Fetch tomorrow's meetings",
    )
    parser.add_argument(
        "--calendar-id",
        default="primary",
        help="Calendar ID to query. Default: primary",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output as JSON array instead of table",
    )
    parser.add_argument(
        "--include-all-day",
        action="store_true",
        help="Include all-day events (excluded by default)",
    )
    return parser.parse_args()


def fetch_events(calendar_id: str, date_str: str) -> list[dict]:
    tz_offset = get_local_utc_offset()
    time_min = f"{date_str}T00:00:00{tz_offset}"
    time_max_date = (
        datetime.strptime(date_str, "%Y-%m-%d") + timedelta(days=1)
    ).strftime("%Y-%m-%d")
    time_max = f"{time_max_date}T00:00:00{tz_offset}"

    params = {
        "calendarId": calendar_id,
        "timeMin": time_min,
        "timeMax": time_max,
        "singleEvents": True,
        "orderBy": "startTime",
    }

    result = subprocess.run(
        [
            "gws",
            "calendar",
            "events",
            "list",
            "--params",
            json.dumps(params),
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"ERROR: gws command failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)

    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as e:
        print(f"ERROR: failed to parse gws output: {e}", file=sys.stderr)
        sys.exit(1)

    return data.get("items", [])


def extract_self_status(attendees: list[dict]) -> str:
    for attendee in attendees:
        if attendee.get("self"):
            return attendee.get("responseStatus", "unknown")
    return "no-rsvp"


def process_events(
    items: list[dict], include_all_day: bool = False
) -> list[dict]:
    meetings = []
    for item in items:
        start = item.get("start", {})
        end = item.get("end", {})

        if "dateTime" not in start:
            if include_all_day:
                meetings.append(
                    {
                        "time": "all-day",
                        "end": "",
                        "status": extract_self_status(
                            item.get("attendees", [])
                        ),
                        "summary": item.get("summary", "?"),
                    }
                )
            continue

        start_time = start["dateTime"][11:16]
        end_time = end.get("dateTime", "")[11:16] if end.get("dateTime") else ""
        status = extract_self_status(item.get("attendees", []))
        summary = item.get("summary", "?")

        meetings.append(
            {
                "time": start_time,
                "end": end_time,
                "status": status,
                "summary": summary,
            }
        )

    return meetings


def main():
    args = parse_args()

    if args.today:
        date_str = datetime.now().strftime("%Y-%m-%d")
    elif args.tomorrow:
        date_str = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")
    elif args.date:
        date_str = args.date
    else:
        date_str = datetime.now().strftime("%Y-%m-%d")

    try:
        datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        print(f"ERROR: invalid date format '{date_str}', use YYYY-MM-DD", file=sys.stderr)
        sys.exit(1)

    items = fetch_events(args.calendar_id, date_str)
    meetings = process_events(items, args.include_all_day)

    if args.json_output:
        print(json.dumps(meetings, indent=2))
    else:
        for m in meetings:
            time_range = f"{m['time']}-{m['end']}" if m['end'] else m['time']
            print(f"{time_range:14s}  {m['status']:15s}  {m['summary']}")


if __name__ == "__main__":
    main()
