#!/usr/bin/python
# Generated By: Claude Code (Claude Opus 4.6)
# Licensed under Apache 2.0
#
# Extract a single tab's content from a Google Doc as plain text.
#
# Usage: gdoc-get-tab.py <document_id> <tab_id>
#
# Fetches the full doc (Docs API doesn't support single-tab fetch),
# finds the matching tab by ID, and converts its content to plain text.
# Requires: gws CLI with docs scope

import json
import subprocess
import sys


def fetch_doc(doc_id: str) -> dict:
    result = subprocess.run(
        [
            "gws", "docs", "documents", "get",
            "--params", json.dumps({
                "documentId": doc_id,
                "includeTabsContent": True,
            }),
        ],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: gws command failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    output = result.stdout
    for line in output.splitlines():
        if line.strip().startswith("{"):
            output = "\n".join(output.splitlines()[output.splitlines().index(line):])
            break
    return json.loads(output)


def find_tab(tabs: list, tab_id: str) -> dict | None:
    for tab in tabs:
        props = tab.get("tabProperties", {})
        if props.get("tabId") == tab_id:
            return tab
        children = tab.get("childTabs", [])
        found = find_tab(children, tab_id)
        if found:
            return found
    return None


def extract_text(content: list) -> str:
    """Convert Google Docs body content to plain text with bullet indentation."""
    lines = []
    for element in content:
        if "paragraph" not in element:
            continue
        para = element["paragraph"]
        style = para.get("paragraphStyle", {})
        named_style = style.get("namedStyleType", "NORMAL_TEXT")

        text_parts = []
        for el in para.get("elements", []):
            if "textRun" in el:
                text_parts.append(el["textRun"]["content"])
            elif "person" in el:
                person = el["person"].get("personProperties", {})
                name = person.get("name", person.get("email", ""))
                text_parts.append(f"@{name}")
            elif "richLink" in el:
                props = el["richLink"].get("richLinkProperties", {})
                title = props.get("title", props.get("uri", ""))
                uri = props.get("uri", "")
                text_parts.append(f"[{title}]({uri})")
            elif "dateElement" in el:
                date_props = el["dateElement"].get("dateElementProperties", {})
                text_parts.append(date_props.get("displayText", ""))

        text = "".join(text_parts).rstrip("\n")
        if not text.strip():
            lines.append("")
            continue

        if named_style == "HEADING_1":
            lines.append(f"# {text}")
        elif named_style == "HEADING_2":
            lines.append(f"## {text}")
        elif named_style == "HEADING_3":
            lines.append(f"### {text}")
        elif "bullet" in para:
            bullet = para["bullet"]
            nesting = bullet.get("nestingLevel", 0)
            indent = "  " * nesting
            text = text.replace("", "").strip()
            text = text.replace("\x0b", "\n" + indent + "  ")
            lines.append(f"{indent}* {text}")
        else:
            text = text.replace("\x0b", "\n")
            lines.append(text)

    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print("Usage: gdoc-get-tab.py <document_id> <tab_id>")
        sys.exit(1)

    doc_id = sys.argv[1]
    tab_id = sys.argv[2]

    doc = fetch_doc(doc_id)
    tabs = doc.get("tabs", [])
    tab = find_tab(tabs, tab_id)

    if not tab:
        print(f"ERROR: tab '{tab_id}' not found", file=sys.stderr)
        sys.exit(1)

    props = tab.get("tabProperties", {})
    print(f"# {props.get('title', '(untitled)')}")
    print()

    body = tab.get("documentTab", {}).get("body", {})
    content = body.get("content", [])
    print(extract_text(content))


if __name__ == "__main__":
    main()
