#!/usr/bin/python
# Generated By: Claude Code (Claude Opus 4.6)
# Licensed under Apache 2.0
#
# List tabs in a Google Doc with nesting structure.
#
# Usage: gdoc-list-tabs.py <document_id>
#
# Output: tab tree with title, tabId, nesting level (JSON)
# Requires: gws CLI with docs scope

import json
import subprocess
import sys


def fetch_tab_structure(doc_id: str) -> dict:
    result = subprocess.run(
        [
            "gws", "docs", "documents", "get",
            "--params", json.dumps({
                "documentId": doc_id,
                "includeTabsContent": True,
                "fields": "tabs(tabProperties,childTabs(tabProperties,childTabs(tabProperties,childTabs(tabProperties))))",
            }),
        ],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: gws command failed: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    output = result.stdout
    for line in output.splitlines():
        if line.strip().startswith("{"):
            output = "\n".join(output.splitlines()[output.splitlines().index(line):])
            break
    return json.loads(output)


def main():
    if len(sys.argv) != 2:
        print("Usage: gdoc-list-tabs.py <document_id>")
        sys.exit(1)

    doc_id = sys.argv[1]
    doc = fetch_tab_structure(doc_id)
    print(json.dumps(doc, indent=2))


if __name__ == "__main__":
    main()
